# HAPI FHIR Genomics Server
FROM ubuntu:16.04
MAINTAINER Gaston A. Fiore <gafiore@alum.mit.edu>
# RUN apt-get update && apt-get install -y TODO



mkdir hapi
cd hapi
wget https://github.com/jamesagnew/hapi-fhir/releases/download/v1.6/hapi-fhir-1.6-cli.tar.bz2
tar -jxvf hapi-fhir-1.6-cli.tar.bz2
